#!/usr/bin/env python3
"""Interactive setup script for pi-gateway."""

import secrets
import shutil
import subprocess
import sys
from pathlib import Path


def prompt(question: str, default: str = "") -> str:
    if default:
        answer = input(f"{question} [{default}]: ").strip()
        return answer or default
    while True:
        answer = input(f"{question}: ").strip()
        if answer:
            return answer
        print("  This field is required.")


def prompt_password(question: str) -> str:
    import getpass
    while True:
        pwd = getpass.getpass(f"{question}: ").strip()
        if len(pwd) >= 8:
            return pwd
        print("  Password must be at least 8 characters.")


def prompt_choice(question: str, options: list) -> str:
    """Prompt user to choose from a list of options."""
    for idx, option in enumerate(options, 1):
        print(f"  {idx}. {option}")
    while True:
        try:
            choice = input(f"\n{question} [1-{len(options)}]: ").strip()
            idx = int(choice) - 1
            if 0 <= idx < len(options):
                return options[idx]
            print(f"  Please enter a number between 1 and {len(options)}")
        except ValueError:
            print("  Please enter a valid number")


def check_dependencies() -> bool:
    ok = True
    for cmd in ["docker"]:
        if not shutil.which(cmd):
            print(f"  ✗ {cmd} not found — please install it first")
            ok = False
        else:
            print(f"  ✓ {cmd} found")

    try:
        subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            check=True,
        )
        print("  ✓ docker compose found")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("  ✗ docker compose not found — please install Docker Compose v2")
        ok = False

    return ok


def main():
    print()
    print("=" * 50)
    print("  Pi Gateway — Setup")
    print("=" * 50)
    print()

    print("Checking dependencies...")
    if not check_dependencies():
        print("\nPlease install missing dependencies and run setup again.")
        sys.exit(1)
    print()

    # Prompt for environment type
    print("Select deployment environment:\n")
    environment = prompt_choice(
        "Environment",
        ["Local Development", "Production (Raspberry Pi)"]
    )
    is_local = environment == "Local Development"
    print()

    env_path = Path(".env")
    if env_path.exists():
        overwrite = input(".env already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            sys.exit(0)

    print("Please provide the following configuration:\n")

    if is_local:
        domain = "localhost"
        acme_email = "local@example.com"
        print(f"  Domain: {domain} (local development)")
        print(f"  ACME Email: {acme_email} (not needed for local)")
    else:
        domain = prompt("Domain (e.g. proxy.example.com)")
        acme_email = prompt("ACME email for Let's Encrypt SSL")

    admin_username = prompt("Admin username", "admin")
    admin_password = prompt_password("Admin password (min 8 chars)")
    api_secret_key = secrets.token_hex(32)

    print()
    print("Generating configuration...")

    env_content = f"""# Pi Gateway Configuration
# Generated by setup.py
# Environment: {environment}

ENVIRONMENT={'local' if is_local else 'production'}
DOMAIN={domain}
ACME_EMAIL={acme_email}

ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_password}

API_SECRET_KEY={api_secret_key}

# Squid container name
SQUID_CONTAINER=squid
"""

    env_path.write_text(env_content)
    print("  ✓ .env created")

    # Setup Caddyfile for environment
    if is_local:
        caddyfile_src = Path("caddy/Caddyfile.local")
        caddyfile_dst = Path("caddy/Caddyfile.active")
        if caddyfile_src.exists():
            caddyfile_dst.write_text(caddyfile_src.read_text())
            print("  ✓ Using Caddyfile.local (local HTTP setup)")
    else:
        caddyfile_src = Path("caddy/Caddyfile")
        caddyfile_dst = Path("caddy/Caddyfile.active")
        if caddyfile_src.exists():
            caddyfile_dst.write_text(caddyfile_src.read_text())
            print("  ✓ Using Caddyfile (production HTTPS setup)")

    domains_txt = Path("squid/domains.txt")
    if not domains_txt.exists():
        domains_txt.touch()
        print("  ✓ squid/domains.txt created")

    print()
    print("=" * 50)
    print("  Setup complete!")
    print("=" * 50)
    print()
    print("Next steps:")
    print()
    print("  1. Build and start:")
    print("       docker compose up --build -d")
    print()

    if is_local:
        print(f"  2. Open http://{domain}")
        print()
        print("  Development mode: HTTPS is disabled (using local certificates)")
        print("  Frontend:  http://localhost:5173 or http://localhost")
        print("  API:       http://localhost:8000")
        print("  Proxy:     http://localhost:3128")
    else:
        print(f"  2. Open https://{domain}")
        print("       (SSL certificate will be issued automatically)")
        print()
        print("  Production mode: Real SSL certificates from Let's Encrypt")
        print(f"  Access:    https://{domain}")
        print("  Proxy:     Configure clients to use http://<server>:3128")

    print()
    print(f"  3. Login with: {admin_username} / <your password>")
    print()
    print("  To stop:    docker compose down")
    print("  To update:  git pull && docker compose up --build -d")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nAborted.")
        sys.exit(1)
