#!/usr/bin/env python3
"""Interactive setup script for pi-gateway."""

import secrets
import sys
from pathlib import Path


def prompt(question: str, default: str = "") -> str:
    if default:
        answer = input(f"{question} [{default}]: ").strip()
        return answer or default
    while True:
        answer = input(f"{question}: ").strip()
        if answer:
            return answer
        print("  This field is required.")


def prompt_password(question: str) -> str:
    import getpass
    while True:
        pwd = getpass.getpass(f"{question}: ").strip()
        if len(pwd) >= 8:
            return pwd
        print("  Password must be at least 8 characters.")


def main():
    print()
    print("=" * 50)
    print("  Pi Gateway — Setup")
    print("=" * 50)
    print()

    env_path = Path(".env")
    if env_path.exists():
        overwrite = input(".env already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Aborted.")
            sys.exit(0)

    print("Please provide the following configuration:\n")

    domain = prompt("Domain (e.g. proxy.example.com)", "localhost")
    acme_email = prompt("ACME email for Let's Encrypt SSL")
    admin_username = prompt("Admin username", "admin")
    admin_password = prompt_password("Admin password (min 8 chars)")
    api_secret_key = secrets.token_hex(32)

    print()
    print("Generating configuration...")

    env_content = f"""# Pi Gateway Configuration
# Generated by setup.py

DOMAIN={domain}
ACME_EMAIL={acme_email}

ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_password}

API_SECRET_KEY={api_secret_key}

# Squid container name (default: pi-gateway-squid-1)
SQUID_CONTAINER=pi-gateway-squid-1
"""

    env_path.write_text(env_content)
    print(f"  ✓ .env created")

    data_dir = Path("data")
    data_dir.mkdir(exist_ok=True)

    for fname in ["passwd", "db.sqlite3"]:
        fpath = data_dir / fname
        if not fpath.exists():
            fpath.touch()
            print(f"  ✓ data/{fname} created")

    domains_txt = Path("squid/domains.txt")
    if not domains_txt.exists():
        domains_txt.touch()
        print(f"  ✓ squid/domains.txt created")

    print()
    print("=" * 50)
    print("  Setup complete!")
    print("=" * 50)
    print()
    print("Next steps:")
    print()
    print("  1. Build and start:")
    print("       docker compose up --build")
    print()
    print(f"  2. Open http://{domain}")
    print()
    print(f"  3. Login with: {admin_username} / <your password>")
    print()

    if domain == "localhost":
        print("  Note: Running on localhost — HTTPS is disabled.")
        print("        For production, set a real domain in .env")
        print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nAborted.")
        sys.exit(1)