http_port 3128

auth_param basic program /usr/lib/squid/basic_ncsa_auth /shared/passwd
auth_param basic realm Proxy
auth_param basic credentialsttl 2 hours
auth_param basic children 5 startup=1 idle=1

acl authenticated proxy_auth REQUIRED
acl proxy_domains dstdomain "/shared/domains.txt"
acl safe_ports port 80 443
acl CONNECT method CONNECT

http_access deny !safe_ports
http_access deny !authenticated
http_access deny CONNECT !proxy_domains
http_access allow proxy_domains
http_access deny all

via off
forwarded_for delete
httpd_suppress_version_string on
coredump_dir /var/spool/squid
access_log daemon:/var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache deny all