"""initial

Revision ID: 2a0569dfa111
Revises: 
Create Date: 2026-03-10 16:48:49.118023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0569dfa111'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ui_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_users_username'), 'ui_users', ['username'], unique=True)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='domainstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['ui_users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['domain_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['ui_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('proxy_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ui_user_id', sa.Integer(), nullable=False),
    sa.Column('pac_token', sa.String(length=128), nullable=False),
    sa.Column('proxy_user', sa.String(length=64), nullable=False),
    sa.Column('proxy_pass', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ui_user_id'], ['ui_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pac_token'),
    sa.UniqueConstraint('proxy_user'),
    sa.UniqueConstraint('ui_user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['ui_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('proxy_users')
    op.drop_table('domains')
    op.drop_index(op.f('ix_ui_users_username'), table_name='ui_users')
    op.drop_table('ui_users')
    op.drop_table('domain_groups')
    # ### end Alembic commands ###
