"""nullable created_by

Revision ID: e3c50cd85820
Revises: 936dc4d20d13
Create Date: 2026-03-14 21:26:20.735442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c50cd85820'
down_revision: Union[str, Sequence[str], None] = '936dc4d20d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               nullable=False)

    # ### end Alembic commands ###
